### ISSUE TITLE
Upload and Multipart Upload Not working

### ISSUE THREAD

**Issue by galileor97** [datopian/r2-bucket-uploader#9]
I cloned this repo and followed all instructions, 

but I am unable to upload files to my R2 bucket. I have not seen any errors in my VS Code. However, I am seeing three errors in my browser console.

1. Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
2. app-index.js:35 [Uppy] [15:24:34] Unexpected token '<', "<!DOCTYPE "... is not valid JSON
3. POST http://localhost:3000/api/multipart-upload/abort-multipart-upload 500 (Internal Server Error)

![Screenshot 2024-03-22 at 15 57 53](https://github.com/datopian/r2-bucket-uploader/assets/44834772/bdfe2fe4-9bbf-4509-9b40-e200fe5b17ff)

**Comment by anuveyatsu** [comment]
@steveoni have you seen this when trying out the library recently?

**Comment by steveoni** [comment]
> @steveoni have you seen this when trying out the library recently?

No

**Comment by anuveyatsu** [comment]
Closing this issue as INVALID. Feel free to reopen this issue or create a new one if the problem arises again.
